# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1259e5d985d860cdd3032da73dee25a51ed2d3859393407732f8ab493affc32157826d624640faf7e6b0e58cbabe712d86416dbbe10dcca2e6867f714723d8a

test:
  secret_key_base: b35c8d69a6e80ce3bd31dcc141009cb0155348fdef43b7da327b76a533fbce7266331420fa0a341a34f194894114ea15b62349be90d82fe2fc6b6f487e2b60fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
